// https://nextjs.org/docs/app/building-your-application/routing/internationalization

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import AppLayout from "./appLayout";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Biru",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [
    { lang: "zh-TW" },
    { lang: "zh-CN" },
    { lang: "en" },
    { lang: "ja" },
    { lang: "ko" },
  ];
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: "zh-TW" | "zh-CN" | "en" | "ja" | "ko" }>;
}>) {
  return (
    <html lang={(await params).lang}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <AppLayout>{children}</AppLayout>
        </Providers>
      </body>
    </html>
  );
}
