// https://nextjs.org/docs/app/building-your-application/routing/internationalization
// https://mui.com/material-ui/customization/css-theme-variables/configuration/#next-js-app-router

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

import AppLayout from "./appLayout";
import { getDictionary } from "./dictionaries";
import Providers from "./providers";

import { locales } from "@/constants/locale";

import InitColorSchemeScript from "@mui/material/InitColorSchemeScript";

import type { LocaleCode } from "@/types/locale";

import { getStores } from "@/utils/stores";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Biru Coffee",
  description: "Generated by create next app",
};

export const generateStaticParams = async () =>
  locales.map((lang) => ({ lang }));

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{
    lang: string;
    // lang: LocaleCode
  }>;
}>) {
  const { lang } = await params;
  const langCode = lang as LocaleCode;
  const dict = await getDictionary(langCode);
  // const dict = await getDictionary(lang);

  const stores = await getStores();
  const fallback = { "/api/stores": stores };

  return (
    <html
      data-scroll-behavior="smooth"
      lang={langCode}
      suppressHydrationWarning
    >
      {/* <html lang={lang} suppressHydrationWarning> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <InitColorSchemeScript attribute="class" />
        <Providers dict={dict} fallback={fallback} lang={langCode}>
          <AppLayout>{children}</AppLayout>
        </Providers>
      </body>
    </html>
  );
}
