// https://nextjs.org/docs/app/guides/internationalization
// https://mui.com/material-ui/customization/css-theme-variables/configuration/#next-js-app-router

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { notFound } from "next/navigation";

import AppLayout from "./appLayout";
import { getDictionary, hasLocale } from "./dictionaries";
import "./globals.css";
import Providers from "./providers";

import { i18n } from "@/i18n-config";

import InitColorSchemeScript from "@mui/material/InitColorSchemeScript";

import { getStores } from "@/utils/stores";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Biru Coffee",
  description: "Generated by create next app",
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_NEXT_URL || "http://localhost:3000",
  ),
};

export const generateStaticParams = async () =>
  i18n.locales.map((lang) => ({ lang }));

const RootLayout = async ({ children, params }: LayoutProps<"/[lang]">) => {
  const { lang } = await params;

  if (!hasLocale(lang)) notFound();

  const dict = await getDictionary(lang);

  const stores = await getStores();
  const fallback = { "/api/stores": stores };

  return (
    <html data-scroll-behavior="smooth" lang={lang} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <InitColorSchemeScript attribute="class" />
        <Providers dict={dict} fallback={fallback} lang={lang}>
          <AppLayout>{children}</AppLayout>
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
